sudo: false
language: rust
rust:
  - nightly
os:
  - linux
cache:
  cargo: true

matrix:
  exclude:
    - if: branch = master and type = push
  include:
    - script:
        - cargo check
        - cargo test
    - addons:
        postgresql: "9.6"
        chrome: stable
      env:
        - MORE_INTERESTING_WEBDRIVER=chrome
        - ROCKET_INIT_USERNAME=root
        - ROCKET_INIT_PASSWORD=ready2go
      before_install:
        - nvm install 10
        - cd test/webdriver && npm ci && cd ../..
        - cd assets && npm install && npm run webpack && cd ..
      install:
        - which diesel || cargo install diesel_cli
        - which chromedriver || (wget https://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip && unzip chromedriver_linux64.zip -d /home/travis/.cargo/bin)
      script:
        - diesel database setup
        - diesel migration run
        - cargo build
        - cargo run &
        - pwd && cd test/webdriver && sh test.sh && cd ../..

branches:
  only:
    - master
    - staging
    - trying
notifications:
  email: false
