[package]
name = "more-interesting-avatar"
version = "0.1.0"
authors = ["Michael Howell <michael@notriddle.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[lib]
path = "lib.rs"

[dependencies]
image = "0.23.7"

